# Generated by Django 5.1.3 on 2024-11-13 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuser',
            name='links_to_social_media',
        ),
        migrations.CreateModel(
            name='LinksToSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_social_media', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('icon_social_media', models.ImageField(blank=True, null=True, upload_to='social_media_icons')),
                ('links_to_social_media', models.URLField(blank=True, max_length=180, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
