# Generated by Django 5.1.3 on 2024-11-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_aboutuser_links_to_social_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuser',
            name='profile_picture_aboutme',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
